version: 2

sources:
  - name: bronze
    database: hive_json_scw
    schema: pokemons
    tables:
      - name: pokemons
      - name: pokemons__abilities
      - name: pokemons__types
      - name: pokemons__stats
      - name: pokemons__moves